
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 32;
  public static final int MULT = 18;
  public static final int OVER = 12;
  public static final int UMINUS = 13;
  public static final int LPAREN = 30;
  public static final int SEMI = 14;
  public static final int REPEAT = 4;
  public static final int INT = 39;
  public static final int LESS = 20;
  public static final int MINUS = 17;
  public static final int WRITE = 7;
  public static final int RPAREN = 31;
  public static final int NOT = 24;
  public static final int SEMICOLON = 28;
  public static final int AND = 26;
  public static final int LT = 9;
  public static final int OR = 25;
  public static final int BOOL = 36;
  public static final int COMMA = 29;
  public static final int DIV = 19;
  public static final int UNTIL = 5;
  public static final int NUM = 44;
  public static final int PLUS = 16;
  public static final int IF = 38;
  public static final int LESSEQ = 21;
  public static final int ASSIGN = 27;
  public static final int ID = 43;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int RBRACKET = 33;
  public static final int EQUAL = 22;
  public static final int error = 1;
  public static final int LCURLY = 34;
  public static final int VOID = 41;
  public static final int EQ = 8;
  public static final int ERROR = 15;
  public static final int RCURLY = 35;
  public static final int TRUTH = 45;
  public static final int TIMES = 11;
  public static final int ELSE = 37;
  public static final int READ = 6;
  public static final int WHILE = 42;
  public static final int NEQUAL = 23;
  public static final int THEN = 2;
  public static final int END = 3;
  public static final int GT = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "THEN",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "EQ",
  "LT",
  "GT",
  "TIMES",
  "OVER",
  "UMINUS",
  "SEMI",
  "ERROR",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LESS",
  "LESSEQ",
  "EQUAL",
  "NEQUAL",
  "NOT",
  "OR",
  "AND",
  "ASSIGN",
  "SEMICOLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LCURLY",
  "RCURLY",
  "BOOL",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "ID",
  "NUM",
  "TRUTH"
  };
}

